### ISSUE TITLE
Can't upgrade to cohort-ktor2:2.0.2

### ISSUE THREAD

**Issue by adomokos** [sksamuel/cohort#42]
Receiving this error:

```
> Task :restserver:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':restserver:compileKotlin'.
> Could not resolve all files for configuration ':restserver:compileClasspath'.
   > Could not find com.sksamuel.cohort:cohort-ktor2:2.0.2.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/sksamuel/cohort/cohort-ktor2/2.0.2/cohort-ktor2-2.0.2.pom
       - https://jitpack.io/com/sksamuel/cohort/cohort-ktor2/2.0.2/cohort-ktor2-2.0.2.pom
     Required by:
         project :restserver
```

Looked [in Maven](https://repo.maven.apache.org/maven2/com/sksamuel/cohort/cohort-ktor2/):

![no-cohort-ktor2](https://github.com/sksamuel/cohort/assets/80530/2e7a0320-46b5-4038-ad59-bcc405982fd2)

**Comment by sksamuel** [comment]
In 2.0 the ktor2 module went away, and the functionality just moved into the core module - since 2.0 no longer supports ktor1.

**Comment by sksamuel** [comment]
See https://github.com/sksamuel/cohort/blob/main/changelog.md#200

**Comment by adomokos** [comment]
Trying to find the [documentation](https://github.com/sksamuel/cohort#how-to-use) for it, no luck:

![incorrect-readme](https://github.com/sksamuel/cohort/assets/80530/77e2e2cc-75fc-41c3-ba70-39e8e792f189)

**Comment by sksamuel** [comment]
yep good shout, I'll update docs.

**Comment by sksamuel** [comment]
Docs updated :)
