### ISSUE TITLE
cohort-ktor2 version `2.0.2` not available in Maven repository

### ISSUE THREAD

**Issue by wiiitek** [sksamuel/cohort#44]
***actual:***

There is version `2.0.2` of `cohort-core`:

- https://central.sonatype.com/artifact/com.sksamuel.cohort/cohort-core/2.0.2
- https://central.sonatype.com/artifact/com.sksamuel.cohort/cohort-core/2.0.2

But the latest version of `cohort-ktor` and `cohort-ktor2` is `1.7.3`:

- https://mvnrepository.com/artifact/com.sksamuel.cohort/cohort-ktor
- https://mvnrepository.com/artifact/com.sksamuel.cohort/cohort-ktor2
- https://central.sonatype.com/artifact/com.sksamuel.cohort/cohort-ktor
- https://central.sonatype.com/artifact/com.sksamuel.cohort/cohort-ktor2

When I clone the project and run `./gradlew publishMavenJavaPublicationToMavenLocal` artifacts are **NOT** created.

I also found the commit that removes `cohort-ktor` and `cohort-ktor2`: [9fe382f1efe8034a14ef3caef7f22ae3bf2db637](https://github.com/sksamuel/cohort/commit/9fe382f1efe8034a14ef3caef7f22ae3bf2db637)

***expected:***

Should we update the documentation about [how to use](https://github.com/sksamuel/cohort#how-to-use) cohort 2.x?

**Comment by sksamuel** [comment]
I've updated the documentation now - you just need the core module.
The ktor2 module has been rolled into the main artifact.
