### ISSUE TITLE
v2.5.0 is not published on maven, I think?

### ISSUE THREAD

**Issue by osoykan** [sksamuel/cohort#47]
Hi,

As the title says, I get not found error, could that be an oversight?

Could not find com.sksamuel.cohort:cohort-core:2.5.0.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/com/sksamuel/cohort/cohort-core/2.5.0/cohort-core-2.5.0.pom
  - https://repo.maven.apache.org/maven2/com/sksamuel/cohort/cohort-core/2.5.0/cohort-core-2.5.0.pom
  - https://plugins.gradle.org/m2/com/sksamuel/cohort/cohort-core/2.5.0/cohort-core-2.5.0.pom
Required by: ...

**Comment by sksamuel** [comment]
core has become kktor
https://github.com/sksamuel/cohort/blob/main/changelog.md#240

**Comment by osoykan** [comment]
Ah my bad, thanks for clearing!
