### ISSUE TITLE
v2.5.0 not on maven central

### ISSUE THREAD

**Issue by JohannesHepp** [sksamuel/cohort#48]
Hey, we update our dependencies via a bot that constantly tries to update this dependency since you released a new version. Unfortunately, it is not on Maven Central. Since it has been two weeks, I wanted to ask when you plan to upload it there. https://mvnrepository.com/artifact/com.sksamuel.cohort/cohort-core

**Comment by sksamuel** [comment]
cohort-core is now cohort-ktor.
See https://github.com/sksamuel/cohort/blob/main/changelog.md
